pipeline:
  identifier: Build_nfinnegan_reactcalculator_1740433991107
  name: Build reactcalculator
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: nfinnegan/reactcalculator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_javascript_app
                  name: Build JavaScript App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      node --version
                      npm install
                      npm run build --if-present
                      npm test
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - stage:
        name: run test step
        identifier: run_test_step
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: npm test
                  description: test
